---
title: "Process"
author: "Yinfeng Zhou"
date: "2021/4/29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load("tidyverse","magrittr","readxl")
```

```{r}
seer<-read.csv("data/SEER File 2.csv")
```

-1: Error  
0: T0  
1: T1  
2: T2  
3: T3  
4: T4a  
5: T4b
```{r}


seer%<>%subset(CS.tumor.size..2004.2015.!="Blank(s)")
seer$CS.tumor.size..2004.2015.%<>%as.numeric()
seer["T Code"]<-ifelse(seer$CS.tumor.size..2004.2015.%in%seq(1,20),1,
                       ifelse(seer$CS.tumor.size..2004.2015.%in%seq(21,50),2,
                              ifelse(seer$CS.tumor.size..2004.2015.%in%seq(51,989),3,-1)))

seer$CS.extension..2004.2015.%<>%as.numeric()

#Hypopharynx
seer["Extension"]<-ifelse(seer$Site.recode.ICD.O.3.WHO.2008=="Hypopharynx",ifelse(seer$CS.extension..2004.2015. %in% c(550,560,565),3,
                          ifelse(seer$CS.extension..2004.2015. %in% c(620,630,635,638),4,
                                 ifelse(seer$CS.extension..2004.2015. %in% c(640,645,650,655,700,760,800,810),5,
                                        ifelse(seer$CS.extension..2004.2015.==950,0,-1)))),-1)

#Tongue
seer$Extension[which(seer$Site.recode.ICD.O.3.WHO.2008=="Tongue")]<-ifelse(seer$CS.extension..2004.2015. %in% c(645,640,650),3,
                          ifelse(seer$CS.extension..2004.2015. %in% c(620,675,710,720,725,735,740,745,750,760,775),4,
                                 ifelse(seer$CS.extension..2004.2015. %in% c(780,788,790,795,800,810),5,
                                        ifelse(seer$CS.extension..2004.2015.==950,0,-1))))

#Floor of Mouth
seer$Extension[which(seer$Site.recode.ICD.O.3.WHO.2008=="Floor of Mouth")]<-ifelse(seer$CS.extension..2004.2015. %in% c(620,635,645,725,760,765,775,780),4,
                                 ifelse(seer$CS.extension..2004.2015. %in% c(788,790,805,810),5,
                                        ifelse(seer$CS.extension..2004.2015.==950,0,-1)))

#GumOther
seer$Extension[which(seer$Site.recode.ICD.O.3.WHO.2008=="Gum and Other Mouth")]<-ifelse(seer$CS.extension..2004.2015. %in% c(720,725,760,770,775),4,
                                 ifelse(seer$CS.extension..2004.2015. %in% c(788,795,805,810),5,
                                        ifelse(seer$CS.extension..2004.2015.==950,0,-1)))

#Salivary Gland
seer$Extension[which(seer$Site.recode.ICD.O.3.WHO.2008=="Salivary Gland")]<-ifelse(seer$CS.extension..2004.2015. %in% c(400,402,405,408),3,
                          ifelse(seer$CS.extension..2004.2015. %in% c(450,510,515,518,00,620,623,625),4,
                                 ifelse(seer$CS.extension..2004.2015. %in% c(655,660,710,790,800,810),5,
                                        ifelse(seer$CS.extension..2004.2015.==950,0,-1))))

#Nasopharynx
seer$Extension[which(seer$Site.recode.ICD.O.3.WHO.2008=="Nasopharynx")]<-ifelse(seer$CS.extension..2004.2015. %in% c(105,205,305,400,500,505,510),1,
                                                                                ifelse(seer$CS.extension..2004.2015. %in% c(555,565,585,590),2,
                                                                                       ifelse(seer$CS.extension..2004.2015. %in% c(605,610,620,645),3,
                                                                                              ifelse(seer$CS.extension..2004.2015. %in% c(800,810),4,
                                                                                                     ifelse(seer$CS.extension..2004.2015.==950,0,-1)))))
#Lip
seer$Extension[which(seer$Site.recode.ICD.O.3.WHO.2008=="Lip")]<-ifelse(seer$CS.extension..2004.2015. %in% c(725,740,750,760,775,778),4,
                                                                        ifelse(seer$CS.extension..2004.2015.%in% c(780,785,788,790,800,910),5,ifelse(seer$CS.extension..2004.2015.==950,0,-1)))

#Nasal Cavity
seer$Extension[which(seer$Site.recode.ICD.O.3.WHO.2008=="Nose, Nasal Cavity and Middle Ear")]<-ifelse(seer$CS.extension..2004.2015. %in% c(105,110,300),1,
                                                                                ifelse(seer$CS.extension..2004.2015. %in% c(200,205,400,410),2,
                                                                                       ifelse(seer$CS.extension..2004.2015. %in% c(610,650,660,670,680),3,
                                                                                              ifelse(seer$CS.extension..2004.2015. %in% c(690,695,705,725),4,
                                                                                                     ifelse(seer$CS.extension..2004.2015.%in% c(730,740,770,780,810),5,ifelse(seer$CS.extension..2004.2015.==950,0,-1))))))

#Oropharynx
seer$Extension[which(seer$Site.recode.ICD.O.3.WHO.2008=="Oropharynx")]<-ifelse(seer$CS.extension..2004.2015. %in% c(530,531,533,535,538,540),3,
                          ifelse(seer$CS.extension..2004.2015. %in% c(610,630,635,650,675,700,705),4,
                                 ifelse(seer$CS.extension..2004.2015. %in% c(708,710,715,718,720,750,770,800,810),5,
                                        ifelse(seer$CS.extension..2004.2015.==950,0,-1))))
seer["Final_T_Code"]<-ifelse(seer$`T Code`>=seer$Extension,seer$`T Code`,seer$Extension)
seer%<>%subset(Final_T_Code!=-1)
seer$Final_T_Code%<>%as.numeric()
```

```{r}
seer%<>%subset(Site.recode.ICD.O.3.WHO.2008%in%c("Other Oral Cavity and Pharynx","Oropharynx" ,"Hypopharynx","Nasopharynx","Salivary Gland"))
```

```{r}
seer$CS.lymph.nodes..2004.2015.%<>%as.numeric()
seer["N Stage"]<-ifelse(seer$CS.lymph.nodes..2004.2015.%in%c(0,10,20,30,40),"N0",
                          ifelse(seer$CS.lymph.nodes..2004.2015.%in%c(100,199,110,120,130,180),"N1",
                                 ifelse(seer$CS.lymph.nodes..2004.2015.%in%c(200,299,210,220,230),"N2",
                                        ifelse(seer$CS.lymph.nodes..2004.2015.%in%c(399,310,330),"N3",ifelse(seer$CS.lymph.nodes..2004.2015.%in%c(400),"N4",NA)))))
seer%<>%na.omit()
seer["T Stage"]<-ifelse(seer$Final_T_Code==1,"T1",
                        ifelse(seer$Final_T_Code==2,"T2",
                               ifelse(seer$Final_T_Code==3,"T3",
                                      ifelse(seer$Final_T_Code==4,"T4a",
                                             ifelse(seer$Final_T_Code==5,"T4b",
                                                    ifelse(seer$Final_T_Code==0,"T0","Error"))))))
seer$Site.recode.ICD.O.3.WHO.2008[seer$Site.recode.ICD.O.3.WHO.2008=="Other Oral Cavity and Pharynx"]<-"Oral Cavity"
```

In the guidelines, the standard therapy for Oropharynx is different, depending on whether it is HPV-negative (marked as n(-)) or HPV-positive (marked as n(+)). However, there is no information in the SEER dataset. Therefore, we will treat all Hypopharynx in the seer dataset as HPV-negative in this report.
```{r}
guidelines<-read_excel("data/NCCN Guidelines.xlsx")
guidelines%<>%subset(`Primary Site`!="Oropharynx \r\n(+) p16")
guidelines$`Primary Site`[guidelines$`Primary Site`=="Oropharynx \r\n(-) p16"]<-"Oropharynx"
```

```{r}
colnames(seer)[6]<-"Primary Site"
seer_final<-inner_join(guidelines,seer,by=c("Primary Site","T Stage","N Stage"))
```

```{r}
unique(seer_final$Reason.no.cancer.directed.surgery)
unique(seer_final$Radiation.recode)
seer_final%<>%subset(Reason.no.cancer.directed.surgery != "Unknown; death certificate; or autopsy only (2003+)")
```

```{r}
seer_final["surgery_standard"]<-rep(0,nrow(seer_final))
seer_final["radiation_standard"]<-rep(0,nrow(seer_final))




for(i in 1:nrow(seer_final)){
  if("Surgery" %in% seer_final[i,4:8]){
  seer_final[i,"surgery_standard"]<-1
  }
  if("Radiation" %in% seer_final[i,4:8]){
  seer_final[i,"radiation_standard"]<-1
  }
  if("Radiation and Chemotherapy" %in% seer_final[i,4:8]){
  seer_final[i,"radiation_standard"]<-1
  }
}
seer_final["surgery_recommended"]<-ifelse(seer_final$Reason.no.cancer.directed.surgery %in% c("Not recommended","Not recommended, contraindicated due to other cond; autopsy only (1973-2002)"),0,1)
seer_final["surgery_refused"]<-ifelse(seer_final$Reason.no.cancer.directed.surgery=="Recommended but not performed, patient refused" ,1,0) 
seer_final["radiation_recommended"]<-ifelse(seer_final$Radiation.recode!="None/Unknown",1,0)
seer_final["radiation_refused"]<-ifelse(seer_final$Radiation.recode=="Refused (1988+)" ,1,0)
```

```{r}
seer_final["Diff_Reco_Sur"]<-ifelse(seer_final$surgery_recommended!=seer_final$surgery_standard,1,0)
seer_final["Diff_Reco_Rad"]<-ifelse(seer_final$radiation_recommended!=seer_final$radiation_standard,1,0)
```

```{r}
# seer_final$Diff_Reco_Rad%<>%factor()
# seer_final$Diff_Reco_Sur%<>%factor()
seer_final%>%group_by(Race.recode..W..B..AI..API.)%>%summarise(p1=sum(Diff_Reco_Sur)/n(),count=n())%>%arrange(desc(p1),.by_group=TRUE)->ce
ggplot(ce, aes(x=reorder(Race.recode..W..B..AI..API.,p1), y=p1)) +geom_bar(stat="identity")+theme(axis.text.x = element_text(angle = 45, hjust = 1))+geom_text(aes(label=round(p1,2)),position=position_dodge(.9))+ggtitle("Percentage of Surgery Recommended different from NCCN Guidlines ")
ggplot(ce, aes(x=reorder(Race.recode..W..B..AI..API.,count), y=count)) +geom_bar(stat="identity")+theme(axis.text.x = element_text(angle = 45, hjust = 1))+geom_text(aes(label=count),position=position_dodge(.9))+ggtitle("Number of Samples")
```